[NBA_API]
url_enfrentamiento = https://stats.nba.com/stats/boxscoresummaryv2
url_jugador = https://stats.nba.com/stats/boxscoretraditionalv2

[HEADERS]
host = stats.nba.com
user_agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
accept = application/json, text/plain, */*
referer = https://www.nba.com/
connection = keep-alive

[GAME_CONFIG]
# Prefijo del ID de partido Competicion (por ejemplo "002" para la temporada regular).
competicion = 002
# Prefijo del ID de partido Temporada (por ejemplo "24" para la temporada 24/25).
temporada = 24
# Nº partido (en la temporada 24/25, el primer partido es el 61)
start_id = 1170
last_id = 938
# Cantidad de partidos a buscar (1230 partidos por temporada)
max_games = 30

[SQL_CONFIG]
# Fichero para insertar los partidos en la base de datos
ficherosql_enfrentamiento = insert_partidos.sql
ficherosql_jugador = insert_jugadores.sql
ficherosql_jugador_partido = insert_jugadores_partido.sql