"use client";

export const columnsEquipo = [
  { accessorKey: "puntos", header: "PTS", tooltip: "Puntos", numeric: true },
  { accessorKey: "asistencias", header: "AST", tooltip: "Asistencias", numeric: true },
  { accessorKey: "rebotes_ofensivos", header: "RO", tooltip: "Rebotes Ofensivos", numeric: true },
  { accessorKey: "rebotes_defensivos", header: "RD", tooltip: "Rebotes Defensivos", numeric: true },
  { accessorKey: "rebotes_totales", header: "RT", tooltip: "Rebotes Totales", numeric: true },
  { accessorKey: "robos", header: "STL", tooltip: "Robos", numeric: true },
  { accessorKey: "tapones", header: "BLK", tooltip: "Tapones", numeric: true },
  { accessorKey: "perdidas_balon", header: "TO", tooltip: "Pérdidas de Balón", numeric: true },
  { accessorKey: "faltas_cometidas", header: "FAL", tooltip: "Faltas Cometidas", numeric: true },
  { accessorKey: "tiros_de_campo_intentados", header: "FGA", tooltip: "Tiros de Campo Intentados", numeric: true },
  { accessorKey: "porcentaje_tiros_de_campo", header: "FG%", tooltip: "Porcentaje de Tiros de Campo", numeric: true },
  { accessorKey: "triples_intentados", header: "3PA", tooltip: "Triples Intentados", numeric: true },
  { accessorKey: "porcentaje_triples", header: "3P%", tooltip: "Porcentaje de Triples", numeric: true },
  { accessorKey: "tiros_de_dos_intentados", header: "2PA", tooltip: "Tiros de Dos Intentados", numeric: true },
  { accessorKey: "porcentaje_tiros_de_dos", header: "2P%", tooltip: "Porcentaje de Tiros de Dos", numeric: true },
  { accessorKey: "porcentaje_efectivo_tiros_de_campo", header: "eFG%", tooltip: "Tiros de Campo Efectivos", numeric: true },
  { accessorKey: "tiros_libres_intentados", header: "FTA", tooltip: "Tiros Libres Intentados", numeric: true },
  { accessorKey: "porcentaje_tiros_libres", header: "FT%", tooltip: "Porcentaje de Tiros Libres", numeric: true },
  { accessorKey: "rating_ofensivo", header: "ORtg", tooltip: "Rating Ofensivo", numeric: true },
  { accessorKey: "rating_defensivo", header: "DRtg", tooltip: "Rating Defensivo", numeric: true },
  { accessorKey: "strength_of_schedule", header: "SOS", tooltip: "Fuerza del Calendario", numeric: true },
  { accessorKey: "simple_rating_system", header: "SRS", tooltip: "Sistema de Rating Simple", numeric: true },
  { accessorKey: "ritmo", header: "Pace", tooltip: "Ritmo", numeric: true },
  { accessorKey: "margen_de_victoria", header: "MOV", tooltip: "Margen de Victoria", numeric: true },
  { accessorKey: "victorias", header: "W", tooltip: "Victorias", numeric: true },
  { accessorKey: "derrotas", header: "L", tooltip: "Derrotas", numeric: true },
];