"use client";

export const columns = [
  { accessorKey: "partidos_jugados", header: "PJ", tooltip: "Partidos Jugados", numeric: true },
  { accessorKey: "minutos_jugados", header: "MIN", tooltip: "Minutos Jugados", numeric: true },
  { accessorKey: "puntos", header: "PTS", tooltip: "Puntos", numeric: true },
  { accessorKey: "asistencias", header: "AST", tooltip: "Asistencias", numeric: true },
  { accessorKey: "rebotes_ofensivos", header: "RO", tooltip: "Rebotes Ofensivos", numeric: true },
  { accessorKey: "rebotes_defensivos", header: "RD", tooltip: "Rebotes Defensivos", numeric: true },
  { accessorKey: "rebotes_totales", header: "RT", tooltip: "Rebotes Totales", numeric: true },
  { accessorKey: "robos", header: "STL", tooltip: "Robos", numeric: true },
  { accessorKey: "tapones", header: "BLK", tooltip: "Tapones", numeric: true },
  { accessorKey: "faltas_cometidas", header: "FAL", tooltip: "Faltas Cometidas", numeric: true },
  { accessorKey: "perdidas_balon", header: "PERD", tooltip: "Pérdidas de Balón", numeric: true },
  { accessorKey: "porcentaje_tiros_de_campo", header: "FG%", tooltip: "Porcentaje de Tiros de Campo", numeric: true },
  { accessorKey: "porcentaje_efectivo_tiros_de_campo", header: "eFG%", tooltip: "Tiros de Campo Efectivos", numeric: true },
  { accessorKey: "porcentaje_triples", header: "3P%", tooltip: "Porcentaje de Triples", numeric: true },
  { accessorKey: "porcentaje_tiros_de_dos", header: "2P%", tooltip: "Porcentaje de Tiros de Dos", numeric: true },
  { accessorKey: "porcentaje_tiros_libres", header: "FT%", tooltip: "Porcentaje de Tiros Libres", numeric: true },
  { accessorKey: "triples_intentados", header: "3PA", tooltip: "Triples Intentados", numeric: true },
  { accessorKey: "tiros_de_dos_intentados", header: "2PA", tooltip: "Tiros de Dos Intentados", numeric: true },
  { accessorKey: "tiros_de_campo_intentados", header: "FGA", tooltip: "Tiros de Campo Intentados", numeric: true },
  { accessorKey: "tiros_libres_intentados", header: "FTA", tooltip: "Tiros Libres Intentados", numeric: true },
  { accessorKey: "player_efficiency_rating", header: "PER", tooltip: "Índice de Eficiencia del Jugador", numeric: true },
  { accessorKey: "box_plus_minus", header: "BPM", tooltip: "Box Plus Minus", numeric: true },
  { accessorKey: "rating_ofensivo", header: "ORtg", tooltip: "Rating Ofensivo", numeric: true },
  { accessorKey: "rating_defensivo", header: "DRtg", tooltip: "Rating Defensivo", numeric: true },
  { accessorKey: "usage_porcentage", header: "USG%", tooltip: "Porcentaje de Uso", numeric: true },
  { accessorKey: "win_share_ofensivo", header: "WSO", tooltip: "Win Share Ofensivo", numeric: true },
  { accessorKey: "win_share_defensivo", header: "WSD", tooltip: "Win Share Defensivo", numeric: true },
  { accessorKey: "win_share_total", header: "WST", tooltip: "Win Share Total", numeric: true },
];