"use client";

export const columns = [
  { accessorKey: "partidos_jugados", header: "PJ", tooltip: "Partidos Jugados" },
  { accessorKey: "minutos_jugados", header: "MIN", tooltip: "Minutos Jugados" },
  { accessorKey: "puntos", header: "PTS", tooltip: "Puntos" },
  { accessorKey: "asistencias", header: "AST", tooltip: "Asistencias" },
  { accessorKey: "rebotes_ofensivos", header: "RO", tooltip: "Rebotes Ofensivos" },
  { accessorKey: "rebotes_defensivos", header: "RD", tooltip: "Rebotes Defensivos" },
  { accessorKey: "rebotes_totales", header: "RT", tooltip: "Rebotes Totales" },
  { accessorKey: "robos", header: "STL", tooltip: "Robos" },
  { accessorKey: "tapones", header: "BLK", tooltip: "Tapones" },
  { accessorKey: "faltas_cometidas", header: "FAL", tooltip: "Faltas Cometidas" },
  { accessorKey: "perdidas_balon", header: "PERD", tooltip: "Pérdidas de Balón" },
  { accessorKey: "porcentaje_tiros_de_campo", header: "FG%", tooltip: "Porcentaje de Tiros de Campo" },
  { accessorKey: "porcentaje_efectivo_tiros_de_campo", header: "eFG%", tooltip: "Tiros de Campo Efectivos" },
  { accessorKey: "porcentaje_triples", header: "3P%", tooltip: "Porcentaje de Triples" },
  { accessorKey: "porcentaje_tiros_de_dos", header: "2P%", tooltip: "Porcentaje de Tiros de Dos" },
  { accessorKey: "porcentaje_tiros_libres", header: "FT%", tooltip: "Porcentaje de Tiros Libres" },
  { accessorKey: "triples_intentados", header: "3PA", tooltip: "Triples Intentados" },
  { accessorKey: "tiros_de_dos_intentados", header: "2PA", tooltip: "Tiros de Dos Intentados" },
  { accessorKey: "tiros_de_campo_intentados", header: "FGA", tooltip: "Tiros de Campo Intentados" },
  { accessorKey: "tiros_libres_intentados", header: "FTA", tooltip: "Tiros Libres Intentados" },
  { accessorKey: "player_efficiency_rating", header: "PER", tooltip: "Índice de Eficiencia del Jugador" },
  { accessorKey: "box_plus_minus", header: "BPM", tooltip: "Box Plus Minus" },
  { accessorKey: "rating_ofensivo", header: "ORtg", tooltip: "Rating Ofensivo" },
  { accessorKey: "rating_defensivo", header: "DRtg", tooltip: "Rating Defensivo" },
  { accessorKey: "usage_porcentage", header: "USG%", tooltip: "Porcentaje de Uso" },
  { accessorKey: "win_share_ofensivo", header: "WSO", tooltip: "Win Share Ofensivo" },
  { accessorKey: "win_share_defensivo", header: "WSD", tooltip: "Win Share Defensivo" },
  { accessorKey: "win_share_total", header: "WST", tooltip: "Win Share Total" },
];
